const cardsData = [
  {
    id: 1,
    img: "swimming",
    rating: "5.0",
    review: 6,
    country: "USA",
    promo: "sold out",
    title: "Life lessons with Katie Zaferes",
    price: 136,
  },
  {
    id: 2,
    img: "wedding",
    rating: "4.9",
    review: 30,
    country: "USA",
    promo: "online",
    title: "Learn wedding photography",
    price: 125,
  },
  {
    id: 3,
    img: "bike",
    rating: "4.8",
    review: 2,
    country: "USA",
    // promo: "sold out",
    title: "Group Mountain Biking",
    price: 50,
  },
  {
    id: 4,
    img: "cooking",
    rating: "4,6",
    review: 4,
    country: "USA",
    promo: "online",
    title: "To cook with the world's  chefs",
    price: 85,
  },
  {
    id: 5,
    img: "singing",
    rating: "4,9",
    review: 10,
    country: "USA",
    promo: "sold out",
    title: "Sing with the stars ",
    price: 180,
  },
]

export default cardsData;